- name: Configure web server
  hosts: web
  become: true

  roles:
    - role: base
      tags: [base]
    - role: ssh
      tags: [ssh]
    - role: nginx
      tags: [nginx]
    - role: app
      tags: [app]
